# Generated by Django 5.2.7 on 2025-11-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docposts',
            name='html_content',
            field=models.TextField(blank=True, help_text='Raw HTML content for the blog post or documentary', null=True),
        ),
    ]
