# Generated by Django 5.2.7 on 2025-11-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image_upload', models.ImageField(blank=True, help_text='Upload an image', null=True, upload_to='media/posts/')),
                ('image_url', models.URLField(blank=True, help_text='Link to an image', null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
